[package]
name = "http-types"
version = "1.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/http-types"
documentation = "https://docs.rs/http-types"
description = "HTTP Types."
keywords = ["http", "types", "standard"]
categories = ["network-programming", "web-programming", "web-programming::http-client", "web-programming::http-server"]
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
readme = "README.md"
edition = "2018"

[dependencies]
url = "2.1.0"
cookie = "0.12.0"
async-std = { version = "0.99.12", default-features = false, features = ["std"] }
pin-project-lite = "0.1.0"
pin-utils = "0.1.0-alpha.4"

[dev-dependencies]
