[package]
name = "http-types"
version = "1.1.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/http-rs/http-types"
documentation = "https://docs.rs/http-types"
description = "Common types for HTTP operations."
keywords = ["http", "types", "request", "response", "h2"]
categories = ["asynchronous", "web-programming", "web-programming::http-client", "web-programming::http-server", "web-programming::websocket"]
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
readme = "README.md"
edition = "2018"

[features]
default = []
unstable = []
hyperium_http = ["http"]

[dependencies]
anyhow = "1.0.26"
cookie = "0.12.0"
infer = "0.1.2"
omnom = "2.1.1"
pin-project-lite = "0.1.0"
url = "2.1.0"

# Note(yoshuawuyts): used for async_std's `channel` only; use "core" once possible.
async-std = { version = "1.4.0", features = ["unstable"] }

# features: hyperium/http
http = { version = "0.2.0", optional = true }

[dev-dependencies]
http = "0.2.0"
