[package]
name = "http-types"
version = "1.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/http-rs/http-types"
documentation = "https://docs.rs/http-types"
description = "Common types for HTTP operations."
keywords = ["http", "types", "request", "response", "h2"]
categories = ["asynchronous", "web-programming", "web-programming::http-client", "web-programming::http-server", "web-programming::websocket"]
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
readme = "README.md"
edition = "2018"

[features]
default = []
hyperium_http = ["http"]

[dependencies]
async-std = { version = "1.4.0", features = ["unstable"] }
cookie = "0.12.0"
infer = "0.1.2"
pin-project-lite = "0.1.0"
url = "2.1.0"
omnom = "2.1.1"

# features: hyperium/http
http = { version = "0.2.0", optional = true }
anyhow = "1.0.26"
type-map = "0.2.0"

[dev-dependencies]
http = "0.2.0"
